#include "builtin_interfaces/msg/Time.idl"

module autoware_auto_vehicle_msgs{
		module msg               {
			@verbatim (language = "comment", text = " Messages to visualize disturbance generator functions  ")
			struct DisturbanceGeneratorReport
				{
				builtin_interfaces::msg::Time stamp;

				@verbatim (language = "comment", text = " test ")
				@default (value = 0.0)
				float steer_original_input;

				@verbatim (language = "comment", text = "test")
				@default (value = 0.0)
				float steer_delayed_input;

				@verbatim (language = "comment", text = "test")
				@default (value = 0.0)
				float steer_time_delay_value;

				@verbatim (language = "comment", text = " test ")
				@default (value = 0.0)
				float acc_original_input;

				@verbatim (language = "comment", text = "test")
				@default (value = 0.0)
				float acc_delayed_input;

				@verbatim (language = "comment", text = "test")
				@default (value = 0.0)
				float acc_time_delay_value;

				@verbatim (language = "comment", text = "test")
				@default (value = 0.0)
				float road_slope_acc;
				};

		};
};

