#include "std_msgs/msg/Header.idl"

module autoware_auto_vehicle_msgs {
  module msg {
    @verbatim (language="comment", text=
      "WheelSpeedReport.msg")
    struct WheelSpeedReport {
      std_msgs::msg::Header header;

      @default (value=0.0)
      float front_left_wheel_speed;
      float front_right_wheel_speed;
      float rear_left_wheel_speed;
      float rear_right_wheel_speed;
    };
  };
};
